//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dynamically_loading_contents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_employee
    {
        public int emp_id { get; set; }
        public string emp_name { get; set; }
        public string emp_email { get; set; }
        public string emp_contact { get; set; }
        public string emp_exp { get; set; }
    }
}
